name: Q6 Workflow
on:
  push:
    paths:
      - Q6.java

jobs:
  archive-and-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Archive Q6.java
        run: |
          echo "Matthias Bernouy" > Q6_archive_date.txt
          echo "$(date +%d-%m-%Y-%H%M%S)" >> Q6_archive_date.txt
          wc -l Q6.java >> Q6_archive_date.txt
          cat Q6.java >> Q6_archive_date.txt

      - name: Calculate differences
        run: |
          if [ -f previous_Q6_archive.txt ]; then
            diff previous_Q6_archive.txt Q6_archive_date.txt > Q6_différences.txt
          fi
          cp Q6_archive_date.txt previous_Q6_archive.txt

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Q6_archive_date.txt Q6_différences.txt
          git commit -m "Added Q6_archive_date.txt and differences"
          git push
